In [6]:
import os
import sys
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import numpy as np
from modules import svd

In [7]:
A = np.array([[3, 2, 2], [2, 3, -2]])

In [8]:
L, sigma, U = svd(A)
L, sigma, U

(array([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]]),
 array([[5., 0., 0.],
        [0., 3., 0.]]),
 array([[-0.70710678, -0.70710678, -0.        ],
        [ 0.23570226, -0.23570226,  0.94280904],
        [-0.66666667,  0.66666667,  0.33333333]]))

In [20]:
def maximum_ratio_sv(L: np.ndarray, sigma: np.ndarray, V: np.ndarray, k: int):
    dsc_singular_values_index = sigma.diagonal().argsort()[::-1]
    max_left_vectors = L[:, dsc_singular_values_index][:, :k]
    max_sigma = sigma[:, dsc_singular_values_index][:, :k]
    max_right_vectors = U[:, dsc_singular_values_index][:, :k]
    return max_left_vectors, max_sigma, max_right_vectors

In [22]:
maximum_ratio_sv(L, sigma, U, 2)

(array([[-0.70710678,  0.70710678],
        [-0.70710678, -0.70710678]]),
 array([[5., 0.],
        [0., 3.]]),
 array([[-0.70710678, -0.70710678],
        [ 0.23570226, -0.23570226],
        [-0.66666667,  0.66666667]]))