In [1]:
import numpy as np

In [10]:
A = np.array([[3, 0], [4, 5]])

In [11]:
A

array([[3, 0],
       [4, 5]])

In [13]:
S = A.T @ A
S

array([[25, 20],
       [20, 25]])

In [15]:
e_values, e_vectors = np.linalg.eig(S)
e_values, e_vectors

(array([45.,  5.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [18]:
s_values = np.sqrt(np.round(np.abs(e_values), 15))
s_values

array([6.70820393, 2.23606798])

In [21]:
np.sqrt(45), np.sqrt(5)

(6.708203932499369, 2.23606797749979)

In [23]:
non_zeros_s_values = s_values[s_values != 0]
non_zeros_s_values

array([6.70820393, 2.23606798])

In [25]:
r_s_vector = e_vectors
r_s_vector

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [26]:
1 / np.sqrt(2)

0.7071067811865475

In [32]:
l_s_vector = np.zeros((r_s_vector.shape[1], s_values.shape[0]), dtype=np.float64)

for i in range(s_values.shape[0]):
    l_s_vector[:, i] = 1 / s_values[i] * (A @ r_s_vector[:, i])

In [35]:
l_s_vector

array([[ 0.31622777, -0.9486833 ],
       [ 0.9486833 ,  0.31622777]])