In [1]:
import numpy as np

In [2]:
A = np.array([[3, 2, 2], [2, 3, -2]])
A

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [3]:
AAt = A @ A.T
AAt

array([[17,  8],
       [ 8, 17]])

In [4]:
AAt_e_values, AAt_e_vectors = np.linalg.eig(AAt)
AAt_e_values, AAt_e_vectors

(array([25.,  9.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [5]:
AtA = A.T @ A
AtA

array([[13, 12,  2],
       [12, 13, -2],
       [ 2, -2,  8]])

In [6]:
AtA_e_values, AtA_e_vectors = np.linalg.eig(AtA)
AtA_e_values, AtA_e_vectors

(array([2.5000000e+01, 5.0324328e-15, 9.0000000e+00]),
 array([[-7.07106781e-01, -6.66666667e-01,  2.35702260e-01],
        [-7.07106781e-01,  6.66666667e-01, -2.35702260e-01],
        [-4.55680392e-17,  3.33333333e-01,  9.42809042e-01]]))

In [7]:
np.round(AtA_e_values)
index_sort_AtA_e_values = np.argsort(AtA_e_values)[::-1]
index_sort_AtA_e_values

array([0, 2, 1])

In [8]:
s_values = np.sqrt(np.round(AtA_e_values, decimals=12))[index_sort_AtA_e_values]
s_values

array([5., 3., 0.])

In [9]:
V = np.round(AtA_e_vectors, decimals=12)[:,index_sort_AtA_e_values]
V

array([[-0.70710678,  0.23570226, -0.66666667],
       [-0.70710678, -0.23570226,  0.66666667],
       [-0.        ,  0.94280904,  0.33333333]])

In [10]:
1 / np.sqrt(18), 4 / np.sqrt(18)

(0.23570226039551587, 0.9428090415820635)

Now we must compute Vt

In [11]:
Vt = V.T
Vt

array([[-0.70710678, -0.70710678, -0.        ],
       [ 0.23570226, -0.23570226,  0.94280904],
       [-0.66666667,  0.66666667,  0.33333333]])

In [12]:
non_zeros_e_values, = np.nonzero(AtA_e_values.round(12))
U = np.zeros((non_zeros_e_values.shape[0], non_zeros_e_values.shape[0]), dtype=np.float64)

for i in range(non_zeros_e_values.shape[0]):
    U[:, i] = 1 / s_values[i] * (A @ V[:, i])
U

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

In [13]:
sigma = np.zeros((U.shape[1], V.shape[0]))
np.fill_diagonal(sigma, s_values)
sigma

array([[5., 0., 0.],
       [0., 3., 0.]])

In [14]:
U

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

In [15]:
sigma

array([[5., 0., 0.],
       [0., 3., 0.]])

In [16]:
Vt

array([[-0.70710678, -0.70710678, -0.        ],
       [ 0.23570226, -0.23570226,  0.94280904],
       [-0.66666667,  0.66666667,  0.33333333]])