In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import numpy as np
from modules import lu_decomposition
from utils.echelon_tools import get_lower_triangular, get_upper_triangular

### LU Decomposition without pivoting

In [3]:
matrix = np.array([[2, 3, 4], [5, 2, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 0)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [4]:
low

array([[ 1.        ,  0.        ,  0.        ],
       [ 2.5       ,  1.        ,  0.        ],
       [ 2.        , -0.18181818,  1.        ]])

In [5]:
up

array([[ 2.        ,  3.        ,  4.        ],
       [ 0.        , -5.5       , -9.        ],
       [ 0.        ,  0.        , -7.63636364]])

In [6]:
low @ up

array([[2., 3., 4.],
       [5., 2., 1.],
       [4., 7., 2.]])

In [7]:
p

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [8]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 0)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

Exception: The diagonal element [1, 1] is Zero

### LU Decomposition with essential pivoting

In [9]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 1)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [10]:
low

array([[1., 0., 0.],
       [2., 1., 0.],
       [2., 0., 1.]])

In [11]:
up

array([[ 2.,  3.,  4.],
       [ 0.,  1., -6.],
       [ 0.,  0., -7.]])

In [12]:
low @ up

array([[2., 3., 4.],
       [4., 7., 2.],
       [4., 6., 1.]])

In [13]:
p

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=int8)

### LU Decomposition with partial pivoting

In [14]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 2)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [15]:
low

array([[1. , 0. , 0. ],
       [1. , 1. , 0. ],
       [0.5, 0. , 1. ]])

In [16]:
up

array([[4. , 6. , 1. ],
       [0. , 1. , 1. ],
       [0. , 0. , 3.5]])

In [17]:
low @ up

array([[4., 6., 1.],
       [4., 7., 2.],
       [2., 3., 4.]])

In [18]:
p

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]], dtype=int8)

### Define matrix 100 * 100

In [38]:
matrix = np.random.rand(100, 100) * 10 + 2

In [39]:
matrix

array([[ 2.80507857, 10.40695468,  6.52745673, ..., 10.13604254,
        10.52990764,  5.76814522],
       [ 7.54085254,  2.22996054,  5.82352876, ...,  9.37186552,
         2.33850968, 10.07053298],
       [ 3.90608068, 10.0113619 ,  7.93974498, ...,  6.70856798,
         4.29663565,  4.82119308],
       ...,
       [ 3.84562308,  2.84051627, 10.36580125, ...,  8.49710473,
         4.16426617,  8.73086534],
       [ 2.30160903,  7.77853846, 10.46647965, ...,  7.10681721,
         2.5363597 ,  4.42050078],
       [ 4.41425262,  2.72713042,  5.33775854, ...,  3.80770059,
         3.5322853 ,  6.76135808]])

In [40]:
np.linalg.matrix_rank(matrix)

100

### LU Decomposition with partial pivoting on 100 * 100 matrix

In [41]:
decompose_matrix_2, pivots_2 = lu_decomposition(matrix, 2)
low_2 = get_lower_triangular(decompose_matrix_2)
up_2 = get_upper_triangular(decompose_matrix_2)

In [42]:
np.testing.assert_array_almost_equal(np.linalg.inv(pivots_2) @ low_2 @ up_2, matrix, decimal=12)

### LU Decomposition with essential pivoting on 100 * 100 matrix

In [43]:
decompose_matrix_1, pivots_1 = lu_decomposition(matrix, 1)
low_1 = get_lower_triangular(decompose_matrix_1)
up_1 = get_upper_triangular(decompose_matrix_1)

In [44]:
np.testing.assert_array_almost_equal(np.linalg.inv(pivots_1) @ low_1 @ up_1, matrix, decimal=12)

AssertionError: 
Arrays are not almost equal to 12 decimals

Mismatched elements: 399 / 10000 (3.99%)
Max absolute difference: 3.6529002e-11
Max relative difference: 6.63375872e-12
 x: array([[ 2.80507857403 , 10.406954677427,  6.527456729637, ...,
        10.136042539966, 10.529907636784,  5.768145218635],
       [ 7.540852544173,  2.229960541116,  5.82352875692 , ...,...
 y: array([[ 2.80507857403 , 10.406954677427,  6.527456729637, ...,
        10.136042539966, 10.529907636784,  5.768145218635],
       [ 7.540852544173,  2.229960541116,  5.82352875692 , ...,...