In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [2]:
import numpy as np
from modules import lu_decomposition
from utils.echelon_tools import get_lower_triangular, get_upper_triangular

### LU Decomposition without pivoting

In [3]:
matrix = np.array([[2, 3, 4], [5, 2, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 0)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [4]:
low

array([[ 1.        ,  0.        ,  0.        ],
       [ 2.5       ,  1.        ,  0.        ],
       [ 2.        , -0.18181818,  1.        ]])

In [5]:
up

array([[ 2.        ,  3.        ,  4.        ],
       [ 0.        , -5.5       , -9.        ],
       [ 0.        ,  0.        , -7.63636364]])

In [6]:
low @ up

array([[2., 3., 4.],
       [5., 2., 1.],
       [4., 7., 2.]])

In [7]:
p

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [8]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 0)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

Exception: The diagonal element [1, 1] is Zero

### LU Decomposition with essential pivoting

In [9]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 1)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [10]:
low

array([[1., 0., 0.],
       [2., 1., 0.],
       [2., 0., 1.]])

In [11]:
up

array([[ 2.,  3.,  4.],
       [ 0.,  1., -6.],
       [ 0.,  0., -7.]])

In [12]:
low @ up

array([[2., 3., 4.],
       [4., 7., 2.],
       [4., 6., 1.]])

In [13]:
p

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]], dtype=int8)

### LU Decomposition with partial pivoting

In [14]:
matrix = np.array([[2, 3, 4], [4, 6, 1], [4, 7, 2]])
decompose_matrix, p = lu_decomposition(matrix, 2)
low = get_lower_triangular(decompose_matrix)
up = get_upper_triangular(decompose_matrix)

In [15]:
low

array([[1. , 0. , 0. ],
       [1. , 1. , 0. ],
       [0.5, 0. , 1. ]])

In [16]:
up

array([[4. , 6. , 1. ],
       [0. , 1. , 1. ],
       [0. , 0. , 3.5]])

In [17]:
low @ up

array([[4., 6., 1.],
       [4., 7., 2.],
       [2., 3., 4.]])

In [18]:
p

array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]], dtype=int8)